name: deploy
on:
  push:
    branches: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23.x
      - name: Install Packages
        run: npm install
      - name: Check Lint
        run: npm run lint
      - name: Test
        run: npm run test -- --coverage
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build Web
        run: npx expo export --platform web
      - name: Deploy Web to Expo
        run: eas deploy
